export const ALL_CATEGORY_REQUEST = "ALL_CATEGORY_REQUEST";
export const ALL_CATEGORY_SUCCESS = "ALL_CATEGORY_SUCCESS";
export const ALL_CATEGORY_FAIL = "ALL_CATEGORY_FAIL";

export const SAVE_ATTR = "SAVE_ATTR";
export const INSERT_CATEGORY = "INSERT_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
