export const ALL_ORDERS_REQUEST_ADMIN = "ALL_ORDERS_REQUEST_ADMIN";
export const ALL_ORDERS_SUCCESS_ADMIN = "ALL_ORDERS_SUCCESS_ADMIN";
export const ALL_ORDERS_FAIL_ADMIN = "ALL_ORDERS_FAIL_ADMIN";
export const ORDER_DETAILS_REQUEST_ADMIN = "ORDER_DETAILS_REQUEST_ADMIN";
export const ORDER_DETAILS_SUCCESS_ADMIN = "ORDER_DETAILS_SUCCESS_ADMIN";
export const ORDER_DETAILS_FAIL_ADMIN = "ORDER_DETAILS_FAIL_ADMIN";

export const MARK_DELIVERD_REQUEST_ADMIN = "MARK_DELIVERD_REQUEST_ADMIN";
export const MARK_DELIVERD_SUCCESS_ADMIN = "MARK_DELIVERD_SUCCESS_ADMIN";
export const MARK_DELIVERD_FAIL_ADMIN = "MARK_DELIVERD_FAIL_ADMIN";

export const ALL_ORDERS_REQUEST = "ALL_ORDERS_REQUEST";
export const ALL_ORDERS_SUCCESS = "ALL_ORDERS_SUCCESS";
export const ALL_ORDERS_FAIL = "ALL_ORDERS_FAIL";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";
export const CREATE_ORDER_RESET = "CREATE_ORDER_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";